// cz-config.js
module.exports = {
  types: [
    { value: "✨ feat", name: "✨ feat: Add a new feature" },
    { value: "🐛 fix", name: "🐛 fix: Fix a bug" },
    { value: "📚 docs", name: "📚 docs: Update documentation" },
    { value: "💄 style", name: "💄 style: Change UI/CSS" },
    { value: "♻️ refactor", name: "♻️ refactor: Refactor code" },
    { value: "🚀 perf", name: "🚀 perf: Improve performance" },
    { value: "✅ test", name: "✅ test: Add tests" },
    { value: "🔧 chore", name: "🔧 chore: Minor tasks" },
    { value: "📦 build", name: "📦 build: Change build system" },
    { value: "👷 ci", name: "👷 ci: Update CI/CD" },
    { value: "⏪ revert", name: "⏪ revert: Revert commit" },
    { value: "🚧 wip", name: "🚧 wip: Work in progress" },
  ],
  messages: {
    type: "Select the type of commit:",
    scope: "\nScope of changes (optional):",
    subject: "Commit title (brief, use imperative mood):\n",
    body: 'Detailed description (optional, use "|" for new line):\n',
    breaking: "Breaking changes (optional):\n",
    footer: "Issues closed (optional, e.g., #123):\n",
    confirmCommit: "Confirm commit?",
  },
  allowCustomScopes: true,
  allowBreakingChanges: ["feat", "fix"],
  skipQuestions: ["body", "breaking", "footer"],
  subjectLimit: 100,
};